baseURL = "https://hughlee.page/"
title = "Hugh's Blog"
theme = "PaperMod"

# 多语言核心
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# 站点通用
pagination.pagerSize = 10
enableRobotsTXT = true
buildFuture = true
enableGitInfo = true

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    # 可选：英文菜单（演示 posts）
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Posts"
        url = "/en/posts/"
        weight = 10

      [[languages.en.menu.main]]
        name = "Search"
        url = "/en/search/"
        weight = 20

      [[languages.en.menu.main]]
        name = "RSS"
        url = "/en/index.xml"
        weight = 99

  [languages.zh]
    languageName = "简体中文"
    weight = 2
    contentDir = "content/zh"
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        name = "文章"
        url = "/zh/posts/"
        weight = 10

      [[languages.zh.menu.main]]
        name = "搜索"
        url = "/zh/search/"
        weight = 20

      [[languages.zh.menu.main]]
        name = "RSS"
        url = "/zh/index.xml"
        weight = 99

# PaperMod 常用最小参数（主题可根据文档再细化）
[params]
  defaultTheme = "auto"   # dark/light 自动
  showReadingTime = true
  showToc = true
  comments = true
  disableSpecial1stPost = true
  search = false
  author = "Hugh"                             # 默认作者
  license = "CC BY-NC-SA 4.0"                 # 默认协议名
  license_url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[params.giscus]
  repo = "HughLee824/blog-comments"   # 你的评论仓库
  repoID = "R_kgDOPa8avA"
  category = "General"
  categoryID = "DIC_kwDOPa8avM4Ct92a"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  crossorigin = "anonymous"

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term     = ["HTML", "RSS"]

