baseURL = "https://blog.indiecraft.app"
title = "Hugh's Blog"
theme = "PaperMod"

# 多语言核心
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# 站点通用
pagination.pagerSize = 10
enableRobotsTXT = true
buildFuture = true

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    # 可选：英文菜单（演示 posts）
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Posts"
        url = "/en/posts/"
        weight = 10

  [languages.zh]
    languageName = "简体中文"
    weight = 2
    contentDir = "content/zh"
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        name = "文章"
        url = "/zh/posts/"
        weight = 10

# PaperMod 常用最小参数（主题可根据文档再细化）
[params]
  defaultTheme = "auto"   # dark/light 自动
  showReadingTime = true
  showToc = true

