[build]
  publish = "public"
  command = "npm ci && npm run build"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https://cdn.jsdelivr.net https://giscus.app https://pagefind.app;
      style-src 'self' 'unsafe-inline' https://giscus.app https://cdn.jsdelivr.net;
      img-src 'self' data:;
      frame-src https://giscus.app;
      connect-src 'self' https://pagefind.app;
      font-src 'self' https://cdn.jsdelivr.net;
      worker-src 'self' blob:;
    """
    Cache-Control = "public, max-age=600"

# 版本化静态资源长缓存（1 年 + immutable）
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/pagefind/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
