[build]
  publish = "public"
  command = "hugo --gc --minify"

[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

