[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

